import os
import re

base_dir = r"c:\Users\Laptop\.gemini\antigravity\scratch\4cups-website"
cafe_path = os.path.join(base_dir, "cafe.html")

# Paths generated by Gemini
img_sources = {
    "6oz": r"C:\Users\Laptop\.gemini\antigravity\brain\cb36bf15-5e39-4f5f-bcd3-73268ecf66ea\gobelet_6oz_1772664899193.png",
    "8oz": r"C:\Users\Laptop\.gemini\antigravity\brain\cb36bf15-5e39-4f5f-bcd3-73268ecf66ea\gobelet_8oz_1772664927962.png",
    "12oz": r"C:\Users\Laptop\.gemini\antigravity\brain\cb36bf15-5e39-4f5f-bcd3-73268ecf66ea\gobelet_12oz_1772664957176.png",
}

for size, src in img_sources.items():
    dest = os.path.join(base_dir, "assets", f"gobelet_{size}.png")
    os.system(f'copy "{src}" "{dest}"')

# Read cafe.html
with open(cafe_path, "r", encoding="utf-8") as f:
    cafe = f.read()

# Replace src="assets/gobelet_simple.png" with src="assets/gobelet_6oz.png" in the 6oz block, etc.
# We can use regex to target the specific blocks.

cafe = re.sub(
    r'(<!-- Gobelet 6 oz -->.*?)src="assets/gobelet_simple.png"(.*?>)',
    r'\1src="assets/gobelet_6oz.png"\2',
    cafe,
    flags=re.DOTALL
)

cafe = re.sub(
    r'(<!-- Gobelet 8 oz -->.*?)src="assets/gobelet_simple.png"(.*?>)',
    r'\1src="assets/gobelet_8oz.png"\2',
    cafe,
    flags=re.DOTALL
)

cafe = re.sub(
    r'(<!-- Gobelet 12 oz -->.*?)src="assets/gobelet_simple.png"(.*?>)',
    r'\1src="assets/gobelet_12oz.png"\2',
    cafe,
    flags=re.DOTALL
)


with open(cafe_path, "w", encoding="utf-8") as f:
    f.write(cafe)

print("✅ cafe.html: Updated 6oz, 8oz, 12oz images to use the specific two-cup generated photos.")
