import os
import re

base_dir = r"c:\Users\Laptop\.gemini\antigravity\scratch\4cups-website"
cafe_path = os.path.join(base_dir, "cafe.html")

# Paths generated by Gemini
img_sources = {
    "4oz": r"C:\Users\Laptop\.gemini\antigravity\brain\cb36bf15-5e39-4f5f-bcd3-73268ecf66ea\gobelet_4oz_clean_1772665147015.png",
    "6oz": r"C:\Users\Laptop\.gemini\antigravity\brain\cb36bf15-5e39-4f5f-bcd3-73268ecf66ea\gobelet_6oz_clean_1772665161294.png",
}

for size, src in img_sources.items():
    dest = os.path.join(base_dir, "assets", f"gobelet_{size}.png")
    os.system(f'copy "{src}" "{dest}" /y')

# Read cafe.html
with open(cafe_path, "r", encoding="utf-8") as f:
    cafe = f.read()

# Replace the 4oz image tag. Right now it has scale(1.6) and says "avec dimensions".
# We'll replace it with a clean one and use scale(0.9) to make it visually the smallest relative to 6oz (scale 1.0)
cafe = re.sub(
    r'(<!-- Gobelet 4 oz -->.*?<div class="detailed-image">\s*)<img.*?>',
    r'\1<img src="assets/gobelet_4oz.png" alt="Gobelet 4 oz blanc" class="w-full h-full object-contain p-0 origin-bottom" style="transform: scale(0.85);">',
    cafe,
    flags=re.DOTALL
)

with open(cafe_path, "w", encoding="utf-8") as f:
    f.write(cafe)

print("✅ cafe.html: Replaced 4oz & 6oz images with clean versions, updated 4oz scaling.")
